### ISSUE TITLE
コンテンツを移植する

### ISSUE THREAD

**Issue by oti** [a11yj/accrefs#3]
https://docs.google.com/document/d/1EiMwdl7J6d7tE5imTZ670PkdTp-rejxaOqiAgjE9TDU/edit#heading=h.kl8vovnhyeq1

上記のドキュメントからコンテンツを移植したいです。移植方法は [README](https://github.com/a11yj/accrefs#ウェブサイトを編集するには) を参考にしてください。

---

- [x] 何から手を着けていいのか分からないときは #1 #30 
- [x] Webアクセシビリティとは？的なもの #1 #30 
- [x] 企業がWebアクセシビリティに取り組む価値 #20 
- [x] Web制作者がWebアクセシビリティに取り組む価値 #21
- [x] 企業ごとのやっていきの表明 #22 
- [x] 組織導入に奮闘している事例 #16 
- [x] 海外の動き #26 
- [x] 障害当事者の声とか使い方 #26
- [x] WCAGやJISの読み方 #26
- [x] ガイドラインのチートシート #9
- [x] WAICのガイドライン系 #17 
- [x] UXデザイン絡み #17 
- [x] インクルーシブデザイン #26
- [x] 要件定義 #26
- [x] 文字サイズ変更機能・読み上げ機能・配色変更機能・スキップリンク #26
- [x] 情報設計・ライティング #26
- [x] alt（代替テキスト） #26
- [x] ビジュアルデザイン #12 
- [x] HTML＋CSS＋JS #23 
- [x] WAI-ARIA #23 
- [x] SVG #23
- [x] アイコンフォント #23
- [x] PDF #23
- [x] 電子書籍（EPUB） #23
- [x] 動画 #23
- [x] AT（支援技術）の使い方などに関するリソース #23
- [x] AS（アクセシビリティサポーテッド情報） #23
- [x] 失敗事例集 #23
- [x] ネイティブアプリ #23
- [x] CMS #29 
- [x] 運用プロセス #29 
- [x] 会社・団体の独自ガイドライン #29 
- [x] チェックツール（コントラスト） #29 
- [x] チェックツール（障害のシミュレーション） #29 
- [x] チェックツール（HTML＋CSS） #29 
- [x] チェック自動化（タスクランナー、CI、E2E） #29 
- [x] Q&A #29 
- [x] 公式仕様および和訳  #15
- [x] おもしろ動画・音楽 #24

**Comment by oti** [comment]
@magi1125 完了したような予感がします。
